### PR TITLE
Patch release 0.2.3

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@shimwell do you mind if I release 0.2.3? I would like to have the fix #27 in the stable version

**Comment by shimwell** [comment]
sure go for it @RemDelaporteMathurin

**Comment by RemDelaporteMathurin** [comment]
The tests are failing for some reason....

**Comment by shimwell** [comment]
oh that is because coolprop does support python 3.9 and I think the docker image is now python 3.9

**Comment by shimwell** [comment]
I have a PR in for the nmm which makes coolprops optional https://github.com/fusion-energy/neutronics_material_maker/pull/16

**Comment by shimwell** [comment]
ok I've updated neutronics material maker, it can be installed in two ways now

basic install
```
pip install neutronics-material-maker
```

install with coolprops that allows equations pressure density temperature for density of coolants
```
pip install neutronics-material-maker[density]
```

try rerunning this CI and it should pip install nnm version  1.1.0 which is the new version and does not include coolprops by default

**Comment by shimwell** [comment]
It looks like moab is not available on the docker image. Not quite sure what is causing that but I can take a look

**Comment by shimwell** [comment]
@RemDelaporteMathurin thanks for all your work on this PR, I can release a new version. Sorry it took me a while to get the tests working. When I get time I shall pop back and simplify the CI

**Pull request merged**
